2024-11-12 15:16:58.175 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:16:59.969 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:16:59.970 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:16:59.970 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:16:59.970 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:17:00.022 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:00.074 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:00.324 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:17:00.335 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:00.338 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:00.339 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:00.341 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:00.524 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/vocabulary.txt HTTP/11" 200 0
2024-11-12 15:17:00.526 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/model.bin HTTP/11" 302 0
2024-11-12 15:17:00.529 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/tokenizer.json HTTP/11" 200 0
2024-11-12 15:17:00.532 - RealTimeSTT: filelock - DEBUG - Attempting to acquire lock 140306154203328 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/7818adb6de9fa3064d3ff81226fdd675be1f6344.lock
2024-11-12 15:17:00.532 - RealTimeSTT: filelock - DEBUG - Attempting to acquire lock 140306154203136 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/dcb76c6586fc06cbdac6dd21f14cfd129cc4cdd9dce19bf4ffa62e59cbe6e6d1.lock
2024-11-12 15:17:00.535 - RealTimeSTT: filelock - DEBUG - Lock 140306154203328 acquired on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/7818adb6de9fa3064d3ff81226fdd675be1f6344.lock
2024-11-12 15:17:00.536 - RealTimeSTT: filelock - DEBUG - Attempting to acquire lock 140306154204240 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/c9074644d9d1205686f16d411564729461324b75.lock
2024-11-12 15:17:00.538 - RealTimeSTT: filelock - DEBUG - Lock 140306154203136 acquired on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/dcb76c6586fc06cbdac6dd21f14cfd129cc4cdd9dce19bf4ffa62e59cbe6e6d1.lock
2024-11-12 15:17:00.538 - RealTimeSTT: filelock - DEBUG - Lock 140306154204240 acquired on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/c9074644d9d1205686f16d411564729461324b75.lock
2024-11-12 15:17:00.539 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): cdn-lfs-us-1.hf.co:443
2024-11-12 15:17:00.682 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/vocabulary.txt HTTP/11" 200 459861
2024-11-12 15:17:00.729 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/config.json HTTP/11" 200 0
2024-11-12 15:17:00.730 - RealTimeSTT: filelock - DEBUG - Attempting to acquire lock 140306154200256 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/3baa18e2b321a2f489614607852a729fcd516480.lock
2024-11-12 15:17:00.731 - RealTimeSTT: filelock - DEBUG - Lock 140306154200256 acquired on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/3baa18e2b321a2f489614607852a729fcd516480.lock
2024-11-12 15:17:00.814 - RealTimeSTT: filelock - DEBUG - Attempting to release lock 140306154204240 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/c9074644d9d1205686f16d411564729461324b75.lock
2024-11-12 15:17:00.814 - RealTimeSTT: filelock - DEBUG - Lock 140306154204240 released on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/c9074644d9d1205686f16d411564729461324b75.lock
2024-11-12 15:17:00.866 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://cdn-lfs-us-1.hf.co:443 "GET /repos/c3/94/c394d9c1034405d7a5fe191992713275237434c7e3bffc5d1345b8134541707f/dcb76c6586fc06cbdac6dd21f14cfd129cc4cdd9dce19bf4ffa62e59cbe6e6d1?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.bin%3B+filename%3D%22model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1731678245&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczMTY3ODI0NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2MzLzk0L2MzOTRkOWMxMDM0NDA1ZDdhNWZlMTkxOTkyNzEzMjc1MjM3NDM0YzdlM2JmZmM1ZDEzNDViODEzNDU0MTcwN2YvZGNiNzZjNjU4NmZjMDZjYmRhYzZkZDIxZjE0Y2ZkMTI5Y2M0Y2RkOWRjZTE5YmY0ZmZhNjJlNTljYmU2ZTZkMT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=P0R~RiWxjOzlTGDtRpXFgMedgEs25dKcDYAB3oK39ccd1KDALmqE6hVM95lYDauFJ6MRek24CyVtklRE8RGBGIlwhtPG3QKEgdWj-s~2UwpnUn4drxx0n~8kCZIVf2OZJ1aJSujUw4zUqM7Q6Z~-lMg4f9j0PBZ7tkL4yZLFikOc6sy7~MkKHdL8vHhdayneSeW~AtsjH3nbEd-2J-EAfzRtAwrFtOOSapM68m1xCuQlRHFHe8SKFKiuq~DWHMblMfUNQMFYHuWxXWoJngpGBUC1m4uv0RW79Kcyvtw8QTCK6evRW0pOYQ9oV~fCOc7yiFuSSWg69IlSYYINrvY9Ug__&Key-Pair-Id=K24J24Z295AEI9 HTTP/11" 200 75538270
2024-11-12 15:17:00.868 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/config.json HTTP/11" 200 2249
2024-11-12 15:17:00.870 - RealTimeSTT: filelock - DEBUG - Attempting to release lock 140306154200256 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/3baa18e2b321a2f489614607852a729fcd516480.lock
2024-11-12 15:17:00.870 - RealTimeSTT: filelock - DEBUG - Lock 140306154200256 released on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/3baa18e2b321a2f489614607852a729fcd516480.lock
2024-11-12 15:17:00.893 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /Systran/faster-whisper-tiny/resolve/d90ca5fe260221311c53c58e660288d3deb8d356/tokenizer.json HTTP/11" 200 2203239
2024-11-12 15:17:01.897 - RealTimeSTT: filelock - DEBUG - Attempting to release lock 140306154203328 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/7818adb6de9fa3064d3ff81226fdd675be1f6344.lock
2024-11-12 15:17:01.897 - RealTimeSTT: filelock - DEBUG - Lock 140306154203328 released on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/7818adb6de9fa3064d3ff81226fdd675be1f6344.lock
2024-11-12 15:17:02.572 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:17:02.572 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:17:02.574 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:17:02.575 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:17:02.575 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:17:02.575 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:17:02.575 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:17:02.575 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:17:02.682 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:17:02.682 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:17:02.683 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:17:02.692 - RealTimeSTT: filelock - DEBUG - Attempting to release lock 140306154203136 on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/dcb76c6586fc06cbdac6dd21f14cfd129cc4cdd9dce19bf4ffa62e59cbe6e6d1.lock
2024-11-12 15:17:02.692 - RealTimeSTT: filelock - DEBUG - Lock 140306154203136 released on /home/michal/.cache/huggingface/hub/.locks/models--Systran--faster-whisper-tiny/dcb76c6586fc06cbdac6dd21f14cfd129cc4cdd9dce19bf4ffa62e59cbe6e6d1.lock
2024-11-12 15:17:02.890 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:17:02.890 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:17:02.890 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:17:02.891 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:17:02.891 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:17:02.891 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:17:03.026 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:06.029 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:09.033 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:12.036 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:15.040 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:18.044 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:21.048 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:24.052 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:27.055 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:30.059 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:33.063 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:36.067 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:39.070 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:42.074 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:45.077 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:46.065 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:17:46.065 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:17:46.066 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:17:46.094 - RealTimeSTT: root - DEBUG - Receive from stdout pipe
2024-11-12 15:17:48.081 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:17:48.087 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:17:48.087 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:17:48.139 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-12 15:17:50.748 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:17:51.584 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:17:51.584 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:17:51.585 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:17:51.585 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:17:51.634 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:51.687 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:17:51.911 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:17:51.973 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:17:51.974 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:17:51.974 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:17:51.975 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:17:51.975 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:17:51.975 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:17:51.975 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:17:51.975 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:17:52.086 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:17:52.086 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:17:52.086 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:17:52.238 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:17:52.238 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:17:52.239 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:17:52.239 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:17:52.239 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:17:52.239 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:17:54.638 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:17:57.641 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:18:00.645 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:18:03.648 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:18:06.652 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:18:09.472 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:18:09.473 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:18:09.475 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:18:09.652 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:18:09.654 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:18:09.654 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:18:09.698 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-12 15:20:26.676 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:20:28.361 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:20:28.361 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:20:28.362 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:20:28.362 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:20:28.413 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:20:28.468 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:20:28.688 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:20:28.746 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:20:28.747 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:20:28.747 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:20:28.747 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:20:28.748 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:20:28.748 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:20:28.748 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:20:28.748 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:20:28.854 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:20:28.854 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:20:28.854 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:20:29.091 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:20:29.091 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:20:29.092 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:20:29.092 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:20:29.092 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:20:29.092 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:20:30.113 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:20:30.114 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:20:30.117 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:20:30.194 - RealTimeSTT: root - DEBUG - Receive from stdout pipe
2024-11-12 15:20:31.418 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:20:31.422 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:20:31.423 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:20:31.495 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-12 15:21:59.495 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:22:01.174 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:22:01.175 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:22:01.178 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:22:01.178 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:22:01.226 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:01.282 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:22:01.491 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:22:01.546 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:22:01.547 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:22:01.547 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:22:01.548 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:22:01.548 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:22:01.548 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:22:01.548 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:22:01.548 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:22:01.657 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:22:01.657 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:22:01.657 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:22:01.879 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:22:01.879 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:22:01.880 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:22:01.880 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:22:01.880 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:22:01.881 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:22:04.230 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:07.233 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:10.237 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:13.241 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:16.245 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:19.249 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:22.253 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:25.256 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:28.259 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:31.262 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:34.265 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:35.223 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:22:35.224 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:22:35.228 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:22:35.266 - RealTimeSTT: root - DEBUG - Receive from stdout pipe
2024-11-12 15:22:37.269 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:22:37.272 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:22:37.272 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:22:37.334 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-12 15:22:39.841 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:22:40.806 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:22:40.806 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:22:40.810 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:22:40.811 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:22:40.861 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:40.920 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:22:41.146 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:22:41.206 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:22:41.206 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:22:41.207 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:22:41.207 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:22:41.207 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:22:41.208 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:22:41.208 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:22:41.208 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:22:41.308 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:22:41.309 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:22:41.309 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:22:41.410 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:22:41.410 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:22:41.410 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:22:41.410 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:22:41.410 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:22:41.411 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:22:43.862 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:46.865 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:49.869 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:52.873 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:55.877 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:22:58.880 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:23:01.882 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:23:03.624 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:23:03.624 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:23:03.631 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:23:04.885 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:23:04.888 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:23:04.888 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:23:04.952 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-12 15:24:00.145 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-12 15:24:01.809 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-12 15:24:01.809 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-12 15:24:01.810 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-12 15:24:01.810 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-12 15:24:01.866 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:24:01.944 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-12 15:24:02.178 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-12 15:24:02.180 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-12 15:24:02.183 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-12 15:24:02.180 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-12 15:24:02.185 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-12 15:24:02.186 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-12 15:24:02.187 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-12 15:24:02.188 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-12 15:24:02.188 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-12 15:24:02.360 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-12 15:24:02.361 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-12 15:24:02.361 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-12 15:24:02.525 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-12 15:24:02.525 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-12 15:24:02.526 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-12 15:24:02.526 - RealTimeSTT: root - INFO - Setting listen time
2024-11-12 15:24:02.526 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-12 15:24:02.526 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-12 15:24:04.869 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-12 15:24:07.434 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-12 15:24:07.434 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-12 15:24:07.436 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-12 15:24:07.873 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-12 15:24:07.875 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-12 15:24:07.875 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-12 15:24:07.921 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2024-11-14 12:24:05.041 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2024-11-14 12:24:06.817 - RealTimeSTT: root - INFO - Initializing faster_whisper main transcription model tiny
2024-11-14 12:24:06.817 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2024-11-14 12:24:06.817 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2024-11-14 12:24:06.817 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2024-11-14 12:24:06.878 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-14 12:24:06.959 - RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-11-14 12:24:07.203 - RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-tiny/revision/main HTTP/11" 200 1848
2024-11-14 12:24:07.220 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-14 12:24:07.222 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
2024-11-14 12:24:07.224 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2024-11-14 12:24:07.232 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
2024-11-14 12:24:07.233 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2024-11-14 12:24:07.234 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.56: cannot open shared object file: No such file or directory
2024-11-14 12:24:07.234 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2024-11-14 12:24:07.234 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-11-14 12:24:07.385 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2024-11-14 12:24:07.385 - RealTimeSTT: root - DEBUG - Starting realtime worker
2024-11-14 12:24:07.385 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2024-11-14 12:24:07.535 - RealTimeSTT: root - DEBUG - Faster_whisper main speech to text transcription model initialized successfully
2024-11-14 12:24:07.535 - RealTimeSTT: root - DEBUG - Main transcription model ready
2024-11-14 12:24:07.535 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2024-11-14 12:24:07.535 - RealTimeSTT: root - INFO - Setting listen time
2024-11-14 12:24:07.536 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2024-11-14 12:24:07.536 - RealTimeSTT: root - DEBUG - Waiting for recording start
2024-11-14 12:24:09.881 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-14 12:24:12.885 - RealTimeSTT: root - ERROR - Microphone connection failed: No input devices found. Retrying...
2024-11-14 12:24:14.029 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2024-11-14 12:24:14.029 - RealTimeSTT: root - DEBUG - Finishing recording thread
2024-11-14 12:24:14.031 - RealTimeSTT: root - DEBUG - Terminating reader process
2024-11-14 12:24:14.046 - RealTimeSTT: root - DEBUG - Receive from stdout pipe
2024-11-14 12:24:15.888 - RealTimeSTT: root - ERROR - Error initializing pyaudio audio recording: Failed to initialize audio stream12 with all sample rates.
Traceback (most recent call last):
  File "/home/michal/Repos/bmw-assist-project-v2/venv/lib/python3.10/site-packages/RealtimeSTT/audio_recorder.py", line 1097, in setup_audio
    raise Exception("Failed to initialize audio stream12 with all sample rates.")
Exception: Failed to initialize audio stream12 with all sample rates.
2024-11-14 12:24:15.889 - RealTimeSTT: root - DEBUG - Terminating transcription process
2024-11-14 12:24:15.889 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2024-11-14 12:24:15.946 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
